wallpaper {
    monitor = HDMI-A-1
    path = ~/Pictures/wallpapers/after-dark.png
    fit_mode = cover
}

wallpaper {
    monitor = DP-1
    path = ~/Pictures/wallpapers/after-dark.png
    fit_mode = cover
}

splash = false

